### PR TITLE
Cleanup and import SKL Feature Pre-processing: OneHotEncoder

### LINKED ISSUE #136: Cleanup and import SKL Feature Pre-processing: OneHotEncoder
We have the original draft of the OneHotEncoder code uploaded in this [branch](https://github.com/microsoft/hummingbird/tree/cleanup/one-hot-enc). All credit here goes to @scnakandala, the original author and brains behind this.

It contains an un-edited implementation of OneHotEncoder [here](https://github.com/microsoft/hummingbird/blob/cleanup/one-hot-enc/hummingbird/ml/operator_converters/one_hot_encoder.py).

There is a single test file [here](https://github.com/microsoft/hummingbird/blob/cleanup/one-hot-enc/tests/test_sklearn_one_hot_encoder_converter.py) that needs to be cleaned up and passing.

Notes:
* We had to treat strings a bit differently because of the way they are represented in tensors
  *  We should add more robust tests here
* the `retain_order`  flag in `OneHotEncoder` is not yet implemented. We can wait on that for later unless someone gets inspired.

### PR DESCRIPTION
**Pull request by TuanNguyen27**
Closes #136

### CODE REVIEW

**Comment by interesaaat** [comment]
Hey @TuanNguyen27 are you still working on this? Otherwise we will likely take over it.

**Comment by TuanNguyen27** [comment]
> Hey @TuanNguyen27 are you still working on this? Otherwise we will likely take over it.

Hi Matteo, sorry i haven't had time. Please feel free to take over

**Comment by ksaur** [comment]
Thanks for getting us started!! :)
this one was hard because of all of the OHE changes in scikit-learn.

**Comment by TuanNguyen27** [comment]
@ksaur yep i was trying to follow sklearn's OHE implementation but i didn't get very far...glad you solved it !

**Pull request closed without merging**
