### PR TITLE
Add float64 support in hummingbird

### LINKED ISSUE #51: float64 issue
At the moment, HB only works with `float32`.  You must cast `float64` to `float32` for correct results.  (You will get an error with the `gemm` algorithm).  We need to fix this.   

Ex:  in  [scikit-learn-random-forest-example.ipynb](https://github.com/microsoft/hummingbird/blob/master/notebooks/scikit-learn-random-forest-example.ipynb) we must cast `X` as follows:
`X = X[0:nrows].astype('|f4')`

### PR DESCRIPTION
**Pull request by KranthiGV**
Addresses issue #51

This PR:
- Add support for float64 input data based on discussion in issue #51 

> It appears Pytorch expects both inputs and model params (weights) to be of the same data type.
> The weights are in float32. In this failure case, the input is float64 type.
> In order to have the same type, it is easier (and computationally efficient) to down cast the inputs.

- Add a few tests around the same change.

Pending:
- I did validate other supported operators as well (Sklearn GBDT, HGBDT; XGB, etc).
Should I add tests for them as well?
- I feel we can update the notebooks (and other examples) as well removing the casting from float64 to float32.
This makes the example simpler and less mysterious. Should I do that?

Validated that all we can now use float32/float64 data.

### CODE REVIEW

**Comment by interesaaat** [comment]
Yes please, can you also fix the notebooks? No need for explicit casting anymore. 

Some test also for the other operators will be helpful yes.

**Comment by KranthiGV** [comment]
Will do them!

**Comment by KranthiGV** [comment]
Segmentation fault when running `LGBM-ONNX-example` notebook (even on master branch).
Looking into why that is happening. 
**UPDATE**: It has probably stemmed up due to my local env. No issues in a newly setup env.

Meanwhile, I updated other notebooks. I will add the additional tests as well.

**Comment by KranthiGV** [comment]
I updated all notebooks but the ONNX runtime based one. Similarly, added tests around all operators but the ONNX runtime based ones. The reason being `onnxruntime only expects single floats (4 bytes) and cannot handle any other kind of floats` from [Common errors with onnxruntime](https://microsoft.github.io/onnxruntime/python/auto_examples/plot_common_errors.html#common-errors-with-onnxruntime)

Let me know if this is okay. Also, please have a look now @interesaaat @ksaur

**Comment by KranthiGV** [comment]
I just noticed that some of my new tests are not being picked up in the PR build. Locally, I see 199 items are collected by pytest but in the PR build, only 188 items are collected. Unsure why this is happening.

**Comment by ksaur** [comment]
Thanks @KranthiGV for adding the notebooks, too! 
I'm very excited about how much nicer this makes usage.

LGTM...  @interesaaat ?

**Comment by ksaur** [comment]
> some of my new tests are not being picked up in the PR build. Locally, I see 199 items are collected by pytest but in the PR build, only 188 items are collected. 

We were having some some issues with the CI/CD system. Runs were failing due to a connectivity to codecov issue. maybe it is related

**Comment by ksaur** [comment]
Ok, codecov is behaving now. :)  (And pytest shouldn't be related to the failures from uploading it to codecov!)

Right now, the main branch shows `178 passed, 4 skipped`, and your run shows `184 passed, 4 skipped`.  Your PR shows 25 new tests. Your `skip-ifs` look right!  So something is weird...  thanks for noticing that!

**Comment by KranthiGV** [comment]
Locally, I pulled latest changes. Later, I validated that between `master` and my working branch, the difference in number of tests picked up is 25 (as expected). I'm trying to identify why there's a discrepancy in the PR build here...(meanwhile I pushed the latest commits)

**Comment by ksaur** [comment]
This PR:
```
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/runner/work/hummingbird/hummingbird
collected 188 items

tests/test_backends.py ....                                              [  2%]
tests/test_lightgbm_converter.py ..................                      [ 11%]
tests/test_no_extra_install.py .ssss                                     [ 14%]
tests/test_onnxml_lightgbm_converter.py ...............                  [ 22%]
tests/test_onnxml_linear_converter.py .....                              [ 25%]
tests/test_onnxml_normalizer_converter.py ....                           [ 27%]
tests/test_onnxml_scaler_converter.py ........                           [ 31%]
tests/test_sklearn_decision_tree_converter.py .......................... [ 45%]
...........                                                              [ 51%]
tests/test_sklearn_gbdt_converter.py .................                   [ 60%]
tests/test_sklearn_histgbdt_converters.py ..............                 [ 67%]
tests/test_sklearn_isolation_forest_converter.py .....                   [ 70%]
tests/test_sklearn_linear_converter.py ...............                   [ 78%]
tests/test_sklearn_normalizer_converter.py ..                            [ 79%]
tests/test_sklearn_one_hot_encoder_converter.py ....                     [ 81%]
tests/test_sklearn_scaler_converter.py ....                              [ 83%]
tests/test_sklearn_sv.py .............                                   [ 90%]
tests/test_xgboost_converter.py ..................                       [100%]

======================= 184 passed, 4 skipped in 35.22s ========================
```

main:
```
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/runner/work/hummingbird/hummingbird
collected 182 items

tests/test_backends.py ....                                              [  2%]
tests/test_lightgbm_converter.py ..................                      [ 12%]
tests/test_no_extra_install.py .ssss                                     [ 14%]
tests/test_onnxml_lightgbm_converter.py ...............                  [ 23%]
tests/test_onnxml_linear_converter.py .....                              [ 25%]
tests/test_onnxml_normalizer_converter.py ....                           [ 28%]
tests/test_onnxml_scaler_converter.py ........                           [ 32%]
tests/test_sklearn_decision_tree_converter.py .......................... [ 46%]
.....                                                                    [ 49%]
tests/test_sklearn_gbdt_converter.py .................                   [ 58%]
tests/test_sklearn_histgbdt_converters.py ..............                 [ 66%]
tests/test_sklearn_isolation_forest_converter.py .....                   [ 69%]
tests/test_sklearn_linear_converter.py ...............                   [ 77%]
tests/test_sklearn_normalizer_converter.py ..                            [ 78%]
tests/test_sklearn_one_hot_encoder_converter.py ....                     [ 80%]
tests/test_sklearn_scaler_converter.py ....                              [ 82%]
tests/test_sklearn_sv.py .............                                   [ 90%]
tests/test_xgboost_converter.py ..................                       [100%]

======================= 178 passed, 4 skipped in 39.49s ========================
```

So `tests/test_sklearn_decision_tree_converter.py` is missing a few I think

Also i need to dig in and see if yours is missing some just due to other commits that will be ok once we merge

**Comment by KranthiGV** [comment]
Missing commits (in my working branch) from the main branch was the key. Now that I merged, the number of tests being picked up are correct and things should be green now. Sorry for the confusion @ksaur. I appreciate your patience.

**Comment by ksaur** [comment]
No problem, glad it's fixed! :)  I'll have matteo glance it over tomorrow then merge. :)

**Comment by interesaaat** [comment]
If the PR is ready I can take a look now.

**Comment by KranthiGV** [comment]
It is ready. Please have a look when you can @interesaaat

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
Thanks @KranthiGV! Now we need to remember to write both float32 and 64 tests for the new ops

**Pull request merged**
