### PR TITLE
sklearn.preprocessing.PolynomialFeatures

### PR DESCRIPTION
**Pull request by ksaur**
Currently this supports only degree 2, and does not support interaction_only

### CODE REVIEW

**Comment by interesaaat** [comment]
@scnakandala any idea what is going on with `interaction_only`?

**Comment by scnakandala** [comment]
Technically it is possible. I think I wanted to prototype it quickly so I restricted the configurations to defaults.
I can have a look at this.

**Comment by interesaaat** [comment]
> Technically it is possible. I think I wanted to prototype it quickly so I restricted the configurations to defaults.
> I can have a look at this.

Ah ok. Don't worry. I thought it was more like a bug. This is not super important, we can merge as is and open an issue.

**Comment by ksaur** [comment]
Rebased, issue filed, ready to merge. :)

**Comment by Hemantr05** [comment]
Does #269 still require fixing?

**Pull request merged**
