### PR TITLE
Add `to` to Pytorch container

### LINKED ISSUE #364: Unable to allocate model to GPU
I'am getting a error if Iam trying to allocate models to a Cuda GPU

Iam using:
Python 3.8
PyTorch 1.7.0 + Cuda 11.0
SciKit-lern 0.23.2
Hummingbird 0.1.0

Windows 10 v2004
Nvidia RTX 3080

Here is a short code snipped that I run:
```
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from hummingbird.ml import convert

import torch

X, y = make_regression(n_features=4, n_informative=2, n_targets = 1, random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)
print(regr.predict([[0, 0, 0, 0]]))


model = convert(regr, 'torch')

prediction = model.predict([[0.0, 0.0, 0.0, 0.0]])
print(prediction)

model = model.to('cuda')
prediction = model.predict(X)
```

At the line `model = model.to('cuda')` I get the following error:
> 'PyTorchSklearnContainerRegression' object has no attribute 'to'

if I step down to **Hummingbird 0.0.6** I get a basicly the same Error at the subsequent line:
> 'PyTorchSklearnContainerRegression' object has no attribute 'predict'

if I also step down **PyTorch to v1.6.0 with Cuda 10.2** the Error seems to be gone, but my RTX 3080 isnt supported by Cuda 10.2, so that dont work for me either

### PR DESCRIPTION
**Pull request by interesaaat**
Closes #364.

### CODE REVIEW

**Comment by interesaaat** [comment]
@speedfreakw  this should fix your problem. Can you please try it?

**Comment by speedfreakw** [comment]
> @speedfreakw this should fix your problem. Can you please try it?

Edit:
Yes that fixes the error! Thank you very much!

I made an mistake in the original anwser. This work:
```
model.to('cuda')
prediction = model.predict(X)
``` 

Orginal:
yes this fixes the 'to' Error, but I'am now getting an other error in the next Line
```
model = model.to('cuda')
prediction = model.predict(X)
```
 `'PyTorchSklearnContainerRegression' object has no attribute 'predict'`

**Comment by interesaaat** [comment]
This is an easy fix.

**Comment by interesaaat** [comment]
@speedfreakw the error should be fixed now.

**Pull request merged**
