### PR TITLE
Add support for `sklearn.mixture.BayesianGaussianMixture`

### PR DESCRIPTION
**Pull request by mshr-h**
#633

### CODE REVIEW

**Comment by mshr-h** [comment]
@ksaur @interesaaat 
Can you review it? Thanks!

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
LGTM. @mshr-h thanks for adding this! I am curios, how fast is this on GPU compared to sklearn?

**Comment by mshr-h** [comment]
@interesaaat 
We haven't benchmarked on the GPU since we are using HB to convert SKL models for microcontrollers through the microTVM. The BGMM->microTVM conversion is not currently available because there's some missing operator support in the PyTorch frontend of the TVM.

But on the CPU (Core i9-10885H), HB is 3x faster than SKL.

**Comment by interesaaat** [comment]
Did you reach out to the TVM folks regarding the missing ops? I am surprised that on CPU we are already 3x faster than SKL!

**Comment by mshr-h** [comment]
> Did you reach out to the TVM folks regarding the missing ops?

Not yet.

**Comment by interesaaat** [comment]
Tagging @masahi, maybe he can help.

**Pull request merged**
