### PR TITLE
Changes for SKL1.2

### PR DESCRIPTION
**Pull request by ksaur**
For #660

### CODE REVIEW

**Comment by ksaur** [comment]
Now we also have 2 other SKL1.2 bugs

```
=========================== short test summary info ============================
FAILED tests/test_sklearn_decomposition.py::TestSklearnMatrixDecomposition::test_pca_converter_mle_whiten - sklearn.utils._param_validation.InvalidParameterError: The 'whiten' parameter of PCA must be an instance of 'bool', an instance of 'numpy.bool_' or an instance of 'int'. Got 'arbitrary-variance' instead.
FAILED tests/test_sklearn_normalizer_converter.py::TestSklearnNormalizer::test_normalizer_converter_raises_wrong_type - sklearn.utils._param_validation.InvalidParameterError: The 'norm' parameter of Normalizer must be a str among {'l1', 'max', 'l2'}. Got 'invalid' instead.
===== 2 failed, 356 passed, 272 skipped, 71 warnings in 184.05s (0:03:04) ======
```

**Comment by ksaur** [comment]
Fixed those two.

And now:

```
=========================== short test summary info ===========================
FAILED tests/test_backends.py::TestBackends::test_onnx_no_test_data_double - AttributeError: 'DecisionTreeRegressor' object has no attribute 'n_features_'
FAILED tests/test_backends.py::TestBackends::test_onnx_no_test_data_float - AttributeError: 'DecisionTreeRegressor' object has no attribute 'n_features_'
FAILED tests/test_extra_conf.py::TestExtraConf::test_onnx_deafault_n_threads - AttributeError: 'DecisionTreeRegressor' object has no attribute 'n_features_'
FAILED tests/test_extra_conf.py::TestExtraConf::test_pandas_batch_onnxml - AttributeError: 'DecisionTreeRegressor' object has no attribute 'n_features_'
===== 4 failed, 522 passed, 104 skipped, 94 warnings in 287.73s (0:04:47) =====
```

**Comment by ksaur** [comment]
@interesaaat this last one seems to be a conflict with sklearn-onnx and SKL1.2.  Double check and we'll open an issue?

The error `'DecisionTreeRegressor' object has no attribute 'n_features_'` is in sklearn-onnx [convert_sklearn_gradient_boosting_classifier](https://github.com/onnx/sklearn-onnx/blob/3c9e0c1a757229f63b94f01cef3a51b638f91f54/skl2onnx/operator_converters/gradient_boosting.py#L36)

And from skl:
[`n_features_` is deprecated in 1.0 and will be removed in 1.2.](https://github.com/scikit-learn/scikit-learn/blob/2cf0f94f49f393d8d08dbf530cdde7e958a3ee99/sklearn/tree/_classes.py#L1054)

**Comment by ksaur** [comment]
Tagging https://github.com/onnx/sklearn-onnx/issues/951 https://github.com/onnx/sklearn-onnx/pull/952

**Comment by interesaaat** [comment]
> @interesaaat this last one seems to be a conflict with sklearn-onnx and SKL1.2. Double check and we'll open an issue?
> 
> The error `'DecisionTreeRegressor' object has no attribute 'n_features_'` is in sklearn-onnx [convert_sklearn_gradient_boosting_classifier](https://github.com/onnx/sklearn-onnx/blob/3c9e0c1a757229f63b94f01cef3a51b638f91f54/skl2onnx/operator_converters/gradient_boosting.py#L36)
> 
> And from skl: [`n_features_` is deprecated in 1.0 and will be removed in 1.2.](https://github.com/scikit-learn/scikit-learn/blob/2cf0f94f49f393d8d08dbf530cdde7e958a3ee99/sklearn/tree/_classes.py#L1054)

Oh I thought that we already fixed this. Let me check.

**Comment by interesaaat** [comment]
Yea we fixed in our code but probably sklern-onnx has not upgraded yet. Good job finding this!

**Comment by ksaur** [comment]
Yes thanks to @mshr-h in https://github.com/microsoft/hummingbird/pull/610 we had `n_features_` already deprecated on our side!

**Comment by mshr-h** [comment]
I've checked [`load_bostom()`](https://scikit-learn.org/1.1/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston) API docs and it says there're two alternatives for that, `fetch_california_housing()` and `fetch_openml(name="house_prices", as_frame=True)` which is called Ames housing dataset.
The former has 20,640 samples in total. But the latter has 506 which is identical to the Boston dataset.
I guess the Ames housing dataset is a better alternative for us because we want to make sure the output of the HB model is close enough to the output of the SKL model.

**Comment by ksaur** [comment]
@mshr-h  I tried the Ames dataset but it has various types, objects:
```
>>> X_train.dtypes
Id             float64
MSSubClass     float64
MSZoning        object
LotFrontage    float64
                ...   
MiscFeature     object
```
 and i want to keep it simple. rather than [encoding](https://www.kaggle.com/questions-and-answers/300552), etc.  Boston was all `float64` and so is Cali.

In the meantime, my https://github.com/onnx/sklearn-onnx/pull/952 was merged (but not released yet).
@interesaaat  should we try to change the pipeline to pull from head to get the change?

**Comment by ksaur** [comment]
I thought these all passed fine (works on my machine!) but it seems with the new `skl2onnx` we have one more:

`TestONNXSVC.test_logistic_regression_onnxml_multi_torch `
```
        for name in names:
>           new_names.append(map[name])
E           KeyError: 'probabilities'`
```

**Review by interesaaat — APPROVED** [review]

**Pull request merged**
