### PR TITLE
Updating Windows runner version

### PR DESCRIPTION
**Pull request by mshr-h**
#659

### CODE REVIEW

**Comment by mshr-h** [comment]
Should be good.

@ksaur @interesaaat 
Can you review it? Thanks!

**Comment by interesaaat** [comment]
Why there is still 2019 in the CI/CD pipeline? It looks that it is stuck there.

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
LGTM but I am not sure if the windows 2019 checks will also block on main.

**Comment by interesaaat** [comment]
Ok solved.

**Pull request merged**
