### PR TITLE
Bump TVM to v0.8

### LINKED ISSUE #530: TVM Conversion:AttributeError: 'String' object has no attribute 'array'
Ran into this issue on latest install of hummingbird. This happens when I load a saved tvm hummingbird model

Stacktrace: 
```
  File "/models/tvm_model.py", line 68, in __init__
    self.model = load(model_path)
  File "/Users/prashanth.harshangi/opt/anaconda3/envs/mlpipe/lib/python3.7/site-packages/hummingbird/ml/_utils.py", line 271, in load
    model = TVMSklearnContainer.load(location, do_unzip_and_model_type_check=False)
  File "/Users/prashanth.harshangi/opt/anaconda3/envs/mlpipe/lib/python3.7/site-packages/hummingbird/ml/containers/sklearn/tvm_containers.py", line 185, in load
    params = load_param_dict(open(os.path.join(location, constants.SAVE_LOAD_TVM_PARAMS_PATH), "rb").read())
  File "/Users/prashanth.harshangi/opt/anaconda3/envs/mlpipe/lib/python3.7/site-packages/hummingbird/ml/containers/sklearn/tvm_containers.py", line 147, in load_param_dict
    return {v.name: v.array for v in load_arr}
  File "/Users/prashanth.harshangi/opt/anaconda3/envs/mlpipe/lib/python3.7/site-packages/hummingbird/ml/containers/sklearn/tvm_containers.py", line 147, in <dictcomp>
    return {v.name: v.array for v in load_arr}
AttributeError: 'String' object has no attribute 'array'
```

Temporarily resolved by updating the param loader in tvm_container to :

```
        def load_param_dict(param_bytes):
            if isinstance(param_bytes, (bytes, str)):
                param_bytes = bytearray(param_bytes)
            load_arr = _load_param_dict(param_bytes)
            # return {v.name: v.array for v in load_arr}
            return {v[0]: np.array(v[1]) for v in load_arr}
```

### PR DESCRIPTION
**Pull request by mshr-h**
[Release Apache TVM v0.8 Release Note · apache/tvm](https://github.com/apache/tvm/releases/tag/v0.8.0)
Fix #530

### CODE REVIEW

**Comment by interesaaat** [comment]
Is something wrong?

**Comment by mshr-h** [comment]
Sorry, I mistakenly closed the PR.

**Comment by ksaur** [comment]
Please rebase to #582 to see if it fixes your issue?  We had a problem with some of the changed packages; it might unblock you

(edit: apparently I can do this by clicking a button; let's see if that works)

**Comment by mshr-h** [comment]
Hi, can you review the PR? @interesaaat @ksaur 
Thanks!

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
Thanks @masahi for updating TVM!

**Comment by mshr-h** [comment]
Thanks @interesaaat for your review.
By the way, I'm @mshr-h, not @masahi.

**Comment by ksaur** [comment]
Hi @mshr-h /@interesaaat, can you please take a look why coverage dropped on this one?

We went from [90% to 80% ](https://codecov.io/github/microsoft/hummingbird?branch=main)in this one commit.  Codecov does mess up sometimes, but I want to make sure that all of the tests that you expect to run are actually running!

opened #589

**Pull request merged**
