### PR TITLE
Updated the dockerfile to be more comfy.

### PR DESCRIPTION
**Pull request by markusweimer**
This changes the Dockerfile to use a devcontainer base image.

Also, this adds a setting to default to `bash` instead of `sh`.

### CODE REVIEW

**Comment by markusweimer** [comment]
This addresses #72

**Comment by interesaaat** [comment]
How close are we with having a single docker file?

**Comment by markusweimer** [comment]
> How close are we with having a single docker file?

I believe the two docker images serve different purposes. The one in `.devcontainer` is for users of VS Code. The one in `.` is for people using the notebooks. Maybe we could base one on the other? Maybe in some hierarchy where the bare bones base image is for the build server, the slightly nicer one for VS Code and the last one is for Notebook users?

**Comment by interesaaat** [comment]
Yes make sense. So should be stick for all images with a version of python? If we are going with 3.6, can you please update the beafy docker image? @ksaur (for visibility)

**Comment by markusweimer** [comment]
> So should be stick for all images with a version of python?

That makes sense, I think. At least for development of hummingbird, sticking to one Python version avoids accidentally moving the requirements to a newer Python version.

**Comment by ksaur** [comment]
I don't think a single docker image is desired at this time because they are two very different purposes.   (I spent hours trying to unify the two files earlier this week, and we discussed offline and decided it was a bad idea.)    Also, since no one really uses codespaces yet, it's really hard to say how it will evolve at this time.

yes sticking to 3.6 python for now.

**Comment by ksaur** [comment]
And the main Dockerfile is also for people doing development in any editor _of their choice_ which may include vscode, not just notebooks.  I don't want to be locked into any particular editor, especially a web-based one.

**Comment by markusweimer** [comment]
> And the main Dockerfile is also for people doing development in any editor of their choice which may include vscode, not just notebooks. I don't want to be locked into any particular editor, especially a web-based one.

Agreed. However, I think that is true for the container definintion in `.devcontainer` as well. There is nothing in the dockerfile which is specific to VS Code. The VS Code specific stuff is in `devcontainer.json` in that folder.

**Comment by markusweimer** [comment]
Shall we update `./Dockerfile` in this PR to use Python 3.6 or make a separate PR for that?

**Comment by ksaur** [comment]
Sure, yes please.  Just do %s/3.7/3.6/g on `./Dockerfile`. Thanks!

I just tested it offline and verified it works.  (i guess some automated testing on `Dockerfile`s would be a nice-to-have, but it would slow down things, so it would have to be outside the regular github actions workflow.)

**Comment by markusweimer** [comment]
Done. `./Dockerfile` now also references Python 3.6

**Pull request merged**
