### PR TITLE
Corrects some typos

### PR DESCRIPTION
**Pull request by melanciani**
- Fix minor typos in convert method and supported functions.
- No issue is referenced as specified in the guidelines

### CODE REVIEW

**Comment by melanciani** [comment]
I'm however not sure about the ONNX parameter sentence : `The *onnx* backend requires a test_input of the initial types, set through the extra_config parameter.` Shouldn't the `set through the extra_config parameter` be removed ?

**Comment by ksaur** [comment]
Hi @RomanBredehoft Thanks for catching these!

> I'm however not sure about the ONNX parameter sentence : `The *onnx* backend requires a test_input of the initial types, set through the extra_config parameter.` Shouldn't the `set through the extra_config parameter` be removed ?

You're right, this is not set through `extra_config`.  I know that things work best with ONNX when the user provides initial input  (ex: `convert(onnx_ml_model, "onnx", Xtest)`), but if they don't we try to [generate it](
https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/convert.py#L168)...not always successfully!

I think we should change this to something like:
`The *onnx* backend works best with a test_input, but we try to generate one if none is provided.`  Thoughts @interesaaat ?

**Comment by interesaaat** [comment]
> Hi @RomanBredehoft Thanks for catching these!
> 
> > I'm however not sure about the ONNX parameter sentence : `The *onnx* backend requires a test_input of the initial types, set through the extra_config parameter.` Shouldn't the `set through the extra_config parameter` be removed ?
> 
> You're right, this is not set through `extra_config`. I know that things work best with ONNX when the user provides initial input (ex: `convert(onnx_ml_model, "onnx", Xtest)`), but if they don't we try to [generate it](https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/convert.py#L168)...not always successfully!
> 
> I think we should change this to something like: `The *onnx* backend works best with a test_input, but we try to generate one if none is provided.` Thoughts @interesaaat ?

Yes, agreed.

**Comment by ksaur** [comment]
Hi @RomanBredehoft , can you make that change on line 414? (`The *onnx* backend works best with a test_input, but we try to generate one if none is provided.`)

**Comment by melanciani** [comment]
@ksaur done ! just rebased and made the change

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
Thanks for the contribution!

**Pull request merged**
