### PR TITLE
adding in py 3.5

### PR DESCRIPTION
**Pull request by ksaur**

### CODE REVIEW

**Comment by interesaaat** [comment]
Good catch!

**Comment by KranthiGV** [comment]
We should do this in pypi as well. It currently shows that one needs Python 3.6+

**Comment by interesaaat** [comment]
Yes. Will update this once we push 0.0.2. Setup.py is already correctly showing >= 3.5.

**Comment by KranthiGV** [comment]
Ah, okay! Didn't realize that. Thanks..

**Pull request merged**
