### PR TITLE
Updating macOS runner version

### PR DESCRIPTION
**Pull request by mshr-h**
#659

### CODE REVIEW

**Comment by mshr-h** [comment]
Python 3.8 failed with the following warning message. But no similar message on 3.9 and 3.10.
Is Python 3.8 on GitHub Actions compiled on older macOS?
> Warning: st.macosx-10.15-x86_64/wheel/tvm/libtvm_runtime.dylib[WARNING] This wheel needs a higher macOS version than the version your Python interpreter is compiled against.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 12_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:

**Comment by mshr-h** [comment]
TVM build on macOS is pretty freaky.

**Comment by mshr-h** [comment]
Maybe [this](https://github.com/pypa/packaging/pull/319) is the cause.

**Comment by mshr-h** [comment]
https://github.com/pypa/cibuildwheel

**Comment by mshr-h** [comment]
The TVM build error on macOS is now fixed.

@ksaur @interesaaat 
Can you review it?
There are still macOS-11 pipeline checks. I don't know how to solve it.

**Review by interesaaat — APPROVED** [review]

**Comment by interesaaat** [comment]
I can solve them. Thanks for saving us the pain of upgrading mac!

**Pull request merged**
