### PR TITLE
[WIP]Investigate #715

### PR DESCRIPTION
**Pull request by mshr-h**
#715

### CODE REVIEW

**Comment by mshr-h** [comment]
> -rw-r--r--  1 runner  staff  42055067 Feb 24 22:03 tvm-0.10.0-cp38-cp38-macosx_10_15_x86_64.whl
-rw-r--r--  1 runner  staff  42055470 Jun 20 02:39 tvm-0.10.0-cp38-cp38-macosx_11_0_x86_64.whl

There are multiple whl  packages in python/dist/ and try to install them simultaneously.
One of them was restored from the cache.
I think we need to exclude python/dist/ from the cache. (Just remove the directory before caching?)

**Comment by ksaur** [comment]
Clearing the cache seems to work, thanks so much for that suggestion!! But I see what you mean, do we also need to exclude the `dist` from the dir before caching?

**Comment by ksaur** [comment]
<del>Now some new [problem](https://github.com/microsoft/hummingbird/actions/runs/5339192071/jobs/9678881224) this time with TVM+pypi; I'm hoping intermittent (will try again in an hour, seems an outage)</del>
Was transient, yay

**Comment by mshr-h** [comment]
Maybe we can avoid the issue by moving the wheel building command to the `Build TVM if Mac` step.

**Pull request closed without merging**
