### PR TITLE
[CI] Upgrade pytorch to 2.4.1

### PR DESCRIPTION
**Pull request by mshr-h**
As per title.

### CODE REVIEW

**Comment by mshr-h** [comment]
We can avoid the below error with updating onnx opset 11->13.

> FAILED tests/test_onnxml_linear_converter.py::TestONNXLinear::test_logistic_regression_onnxml_binary - onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/_operators.0/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{100}, requested shape:{1}

**Comment by mshr-h** [comment]
torch==2.4.1 worked fine.

**Comment by mshr-h** [comment]
@ksaur Can you take a look at it? Thanks!

**Review by ksaur — APPROVED** [review]
Thanks for fixing this! :)

**Pull request merged**
